AEROGEAR-2630 - Add create client build form.
aerogear/origin-web-console pull request #41
Opened 2018-05-16 11:02 UTC by mikenairn

* Create jenkins pipeline build config for android applications.
* Enable "Create Build" option only when mobile CI/CD provisioned and client type is Android

**Verification:**

* Create project with Mobile CI/CD provisioned and an android client
* Select "Create Build" from the android clients action menu
* Create a new build for a public repo, debug build type, start the pipeline and verify it completes
* Create a new build for a private repo, debug build type, start the pipeline and verify it completes
* Create a new build for a public repo, release build type, start the pipeline and verify it completes
* Create a new build for a private repo, release build type, start the pipeline and verify it completes

To create a test keystore certificate, use the following:

```
keytool -genkey -v -keystore testcert.keystore -alias testcert -keyalg RSA -keysize 2048 -validity 10000
keytool -importkeystore -srckeystore testcert.keystore -destkeystore testcert.p12 -deststoretype PKCS12 -srcalias testcert
```

2018-05-16 11:20 UTC, sedroche approved these changes

2018-05-16 11:20 UTC, sedroche commented on app/scripts/controllers/mobileClients.js
> +                _.each($scope.serviceInstances, function (serviceInstance) {
Can do:

```.js
ctrl.mobileCIEnabled = _.some($scope.serviceInstances, function(serviceInstance) {
  return /aerogear-digger/.test(serviceInstance.metadata.name);
});
```

2018-05-16 12:34 UTC, vchepeli requested changes

2018-05-16 12:34 UTC, ghost commented on app/scripts/controllers/createClientBuild.js
> +                  name: 'FH_CONFIG_CONTENT',
Do we still need 'FH_CONFIG_CONTENT'?

2018-05-16 12:34 UTC, ghost commented on app/scripts/controllers/mobileClients.js
> +                    ctrl.mobileCIEnabled = true;
does not `break` needed here?

2018-05-17 09:09 UTC, mikenairn commented on app/scripts/controllers/mobileClients.js
> +                _.each($scope.serviceInstances, function (serviceInstance) {
:+1 Updated

2018-05-17 09:12 UTC, mikenairn commented on app/scripts/controllers/createClientBuild.js
> +                  name: 'FH_CONFIG_CONTENT',
Removed.

If we have no intention of using it in 5.x, i don't think we should have it here. It does however mean the default Jenkinsfile no longer works, so we should update the example to make this optional https://github.com/aerogear/aerogear-digger/blob/master/jenkinsfiles/android_jenkinsfile.groovy#L10.

@odra @maleck13 Does that makes sense to you?

2018-05-17 09:54 UTC, mikenairn commented on app/scripts/controllers/createClientBuild.js
> +                  name: 'FH_CONFIG_CONTENT',
Made changes to this Jenkinsfile to allow it work with the build config generated here https://github.com/mikenairn/helloworld-android-gradle/commit/447f346d35e37d37852c279f4d620a660e40ae88

2018-05-17 09:57 UTC, maleck13 commented on app/scripts/controllers/createClientBuild.js
> +                  name: 'FH_CONFIG_CONTENT',
Yes this makes sense to me. Did we create a follow on issue to allow env vars to be specified when creating the build?

2018-05-17 14:42 UTC, mikenairn commented
Changing the base branch on here didn't work quite how i expected (it's still listing more changes than there really are), so closing this in favour of https://github.com/aerogear/origin-web-console/pull/43

2018-05-17 14:42 UTC, closed without merging