[AEROGEAR-2734] List mobile builds in client overview
aerogear/origin-web-console pull request #48
Opened 2018-05-23 14:15 UTC by dimitraz

**Description**
List the latest 5 builds of the mobile client
The build link should point to its pipeline build view

**Related Jira**
[AEROGEAR-2734](https://issues.jboss.org/browse/AEROGEAR-2734)

2018-05-23 14:15 UTC, dimitraz commented
@JameelB

2018-05-24 06:40 UTC, vchepeli requested changes

2018-05-24 06:40 UTC, vchepeli commented on app/scripts/directives/overview/mobileClientRow.js
> +        row.builds = _.map(row.builds, function(buildArray) {
same here, assign result to new variable

2018-05-24 06:40 UTC, vchepeli commented on app/scripts/directives/overview/mobileClientRow.js
> +        row.builds = _.slice(orderObjectsByDate(row.builds, true), 0, 5);
same here, assign result to new variable

2018-05-24 06:40 UTC, vchepeli commented on app/scripts/directives/overview/mobileClientRow.js
> +        row.builds = _.groupBy(row.builds, function(build) {
Do not assign to same variable or create copy of `row.builds`

2018-05-24 06:40 UTC, vchepeli commented on app/scripts/directives/overview/mobileClientRow.js
> +      var kind = 'BuildConfig';
`const KIND = 'BuildConfig';` ?

2018-05-24 09:06 UTC, sedroche commented on app/scripts/directives/overview/mobileClientRow.js
> +        row.builds = _.slice(orderObjectsByDate(builds, true), 0, 5);
I prefer to keep filters within the html as much as possible. There is a `limitTo` filter which can be used along with `orderObjectsByDate`

2018-05-24 09:06 UTC, sedroche commented on app/views/overview/_mobile-client-row.html
> +                    <span class="build-status-icon" ng-if="build.status.phase.toLowerCase() === 'running'"><i class="fa fa-refresh"></i></span>
Can we use the exact html used in the pipelines page I think its in `views/directives/_build-pipeline-expanded.html`

2018-05-24 09:06 UTC, sedroche commented on app/scripts/directives/overview/mobileClientRow.js
> +        var groupedBuilds = _.groupBy(filteredBuilds, function(build) {
I believe we are showing the last five builds so we aren't grouping by buildconfig

2018-05-25 09:25 UTC, vchepeli approved these changes

2018-05-25 14:14 UTC, dimitraz commented
@sedroche @vchepeli rebased, can you take another look?

2018-05-29 09:48 UTC, JameelB commented on app/views/overview/_mobile-client-row.html
> +              <a href="" ng-href="{{ row.navigateToMobileServices() }}">Bind them to use with this client.</a>
This needs to be changed to `row.navigateToMobileTab()`

2018-05-29 09:52 UTC, JameelB approved these changes

2018-05-29 09:52 UTC, merged